Repository IAMconsortium/pyam, pull requests merged in 2020-10, with the labels that each got.

#431 Bugfix when replacing index values leads to duplicates
  pyam/index.py
  tests/test_index.py
Labels: bug, data back-end

#436 Raise an error with appending mismatching timeseries index dimensions
  RELEASE_NOTES.md
  pyam/core.py
  tests/test_feature_append_rename.py
Labels: bug, data back-end

#433 Rewrite the data-model page in the docs
  doc/source/data.rst
Labels: data back-end

#429 Fix return type of validation after data refactoring
  RELEASE_NOTES.md
  pyam/core.py
  tests/test_core.py
  tests/test_feature_validation.py
Labels: data back-end

#439 Fix for `aggregate_region()` to work with extra-columns
  pyam/_aggregate.py
Labels: bug, extra-cols

#432 Add attributes to access index dimensions
  RELEASE_NOTES.md
  doc/source/tutorials/pyam_first_steps.ipynb
  pyam/core.py
  tests/test_core.py
  tests/test_feature_append_rename.py
Labels: enhancement

#440 Add `boxplot()` visualization feature
  RELEASE_NOTES.md
  doc/source/_examples/README.txt
  doc/source/_examples/data.csv
  doc/source/_examples/plot_bar.py
  doc/source/_examples/plot_bar_with_net_lines.py
  doc/source/_examples/plot_boxplot.py
  doc/source/_examples/plot_pie.py
  doc/source/_examples/plot_ranges.py
  doc/source/_examples/plot_stack.py
  doc/source/_examples/plot_timeseries.py
  doc/source/_examples/tutorial_data.csv
  pyam/core.py
  pyam/plotting.py
  tests/expected_figs/test_boxplot.png
  tests/expected_figs/test_boxplot_hue.png
  tests/test_plotting.py
Labels: plotting

#445 Prevent conflicts between attributes and data/meta columns
  RELEASE_NOTES.md
  pyam/core.py
  pyam/utils.py
  tests/test_core.py
Labels: bug, extra-cols

#444 Use warnings module for deprecation warning
  RELEASE_NOTES.md
  pyam/logging.py
Labels: enhancement, logging
