Repository IAMconsortium/pyam, pull requests merged in 2021-08, with the labels that each got.

#566 updated colors, making a commit to start a PR
  RELEASE_NOTES.md
  pyam/plotting.py
  tests/expected_figs/test_line_PYAM_COLORS.png
Labels: plotting

#561 Make `rename()` work with a custom index
  pyam/core.py
  tests/conftest.py
Labels: generic-index-cols

#572 Loosen xlrd requirement
  .github/workflows/pytest-dependency.yml
  RELEASE_NOTES.md
  pyam/core.py
  pyam/utils.py
  setup.py
  tests/test_io.py
Labels: dependencies
