Repository IAMconsortium/pyam, pull requests merged in 2021-03, with the labels that each got.

#499 Implement `order` option in line plot
  RELEASE_NOTES.md
  pyam/core.py
  pyam/index.py
  pyam/plotting.py
  pyam/unfccc.py
  pyam/utils.py
  tests/expected_figs/test_line_PYAM_COLORS.png
  tests/expected_figs/test_line_filter_title.png
  tests/expected_figs/test_line_plot.png
  tests/expected_figs/test_line_plot_bottom_legend.png
  tests/expected_figs/test_line_plot_dict_legend.png
  tests/expected_figs/test_line_plot_order_by_dict.png
  tests/expected_figs/test_line_plot_order_by_rc.png
  tests/test_plotting.py
Labels: plotting

#508 Bugfix for non-empty invisible header in 'meta' sheet
  RELEASE_NOTES.md
  pyam/utils.py
  tests/data/empty_meta_sheet.xlsx
  tests/test_io.py
Labels: bug

#503 Fix timeseries regressions
  pyam/core.py
  tests/conftest.py
  tests/test_core.py
Labels: enhancement

#510 Improve performance of `pyam.concat()`
  AUTHORS.rst
  RELEASE_NOTES.md
  pyam/core.py
  tests/conftest.py
  tests/test_core.py
Labels: enhancement
